"""add_max_delivery_km_to_restaurant_config

Revision ID: 188c330a2fc6
Revises: 2d79af4c822b
Create Date: 2026-04-06 21:57:44.218727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188c330a2fc6'
down_revision: Union[str, Sequence[str], None] = '2d79af4c822b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_configs', sa.Column('max_delivery_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_configs', 'max_delivery_km')
    # ### end Alembic commands ###
