"""add restaurant_config table

Revision ID: fc88913aa563
Revises: fdc77e5f0c13
Create Date: 2026-04-04 18:47:34.592863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc88913aa563'
down_revision: Union[str, Sequence[str], None] = 'fdc77e5f0c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('accept_orders', sa.Boolean(), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=True),
    sa.Column('midday_delivery', sa.Boolean(), nullable=True),
    sa.Column('evening_delivery', sa.Boolean(), nullable=True),
    sa.Column('pickup', sa.Boolean(), nullable=True),
    sa.Column('onsite', sa.Boolean(), nullable=True),
    sa.Column('reservation', sa.Boolean(), nullable=True),
    sa.Column('all_you_can_eat', sa.Boolean(), nullable=True),
    sa.Column('a_la_carte', sa.Boolean(), nullable=True),
    sa.Column('payment_online', sa.Boolean(), nullable=True),
    sa.Column('payment_onsite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurant_configs_id'), 'restaurant_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_configs_id'), table_name='restaurant_configs')
    op.drop_table('restaurant_configs')
    # ### end Alembic commands ###
